# version: '3.8'

services:
  nginx:
    # image: local-nginx
    image: nginx-server:latest 
    ports:
      - "80:80"
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.confi
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-network

  python-app:
    # image: local-python-app
    image: python-app:latest 
    container_name: python_app
    expose:
      # - "eight thousand"
      - "8000"
    networks:
      - nginx-network

networks:
  nginx-network:
    # driver: bridg
    driver: bridge
    # options:
    #   compelex_option: value
